{
  "status": "fail",
  "tests": [
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-1",
      "status": "error",
      "test_code": "(is (zero? (sum-of-multiples/sum-of-multiples (quote (3 5)) 1)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-4",
      "status": "error",
      "test_code": "(is (= 3 (sum-of-multiples/sum-of-multiples (quote (3 5)) 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-10",
      "status": "error",
      "test_code": "(is (= 23 (sum-of-multiples/sum-of-multiples (quote (3 5)) 10)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-100",
      "status": "error",
      "test_code": "(is (= 2318 (sum-of-multiples/sum-of-multiples (quote (3 5)) 100)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-1000",
      "status": "error",
      "test_code": "(is (= 233168 (sum-of-multiples/sum-of-multiples (quote (3 5)) 1000)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-20-using-7-13-17",
      "status": "error",
      "test_code": "(is (= 51 (sum-of-multiples/sum-of-multiples (quote (7 13 17)) 20)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-15-using-4-6",
      "status": "error",
      "test_code": "(is (= 30 (sum-of-multiples/sum-of-multiples (quote (4 6)) 15)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-150-using-5-6-8",
      "status": "error",
      "test_code": "(is (= 4419 (sum-of-multiples/sum-of-multiples (quote (5 6 8)) 150)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-51-using-5-25",
      "status": "error",
      "test_code": "(is (= 275 (sum-of-multiples/sum-of-multiples (quote (5 25)) 51)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-10_000-using-43-47",
      "status": "error",
      "test_code": "(is (= 2203160 (sum-of-multiples/sum-of-multiples (quote (43 47)) 10000)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-100-using-1",
      "status": "error",
      "test_code": "(is (= 4950 (sum-of-multiples/sum-of-multiples (quote (1)) 100)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (2) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "sum-to-10_000-using-empty",
      "status": "error",
      "test_code": "(is (zero? (sum-of-multiples/sum-of-multiples (quote ()) 10000)))"
    }
  ],
  "version": 2
}
