{
  "status": "fail",
  "tests": [
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-1-is-decimal-1",
      "status": "error",
      "test_code": "(testing \"1 should still be 1\" (is (= 1 (to-decimal \"1\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-2-is-decimal-2",
      "status": "error",
      "test_code": "(testing \"2 should still be 2\" (is (= 2 (to-decimal \"2\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-10-is-decimal-3",
      "status": "error",
      "test_code": "(testing \"10 should be 3\" (is (= 3 (to-decimal \"10\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-11-is-decimal-4",
      "status": "error",
      "test_code": "(testing \"11 should be 4\" (is (= 4 (to-decimal \"11\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-100-is-decimal-9",
      "status": "error",
      "test_code": "(testing \"100 should be 9\" (is (= 9 (to-decimal \"100\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-112-is-decimal-14",
      "status": "error",
      "test_code": "(testing \"112 should be 14\" (is (= 14 (to-decimal \"112\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-222-is-decimal-26",
      "status": "error",
      "test_code": "(testing \"222 should be 26\" (is (= 26 (to-decimal \"222\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "trinary-1122000120-is-decimal-32091",
      "status": "error",
      "test_code": "(testing \"1122000120 should be 32091\" (is (= 32091 (to-decimal \"1122000120\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "invalid-input-is-decimal-0",
      "status": "error",
      "test_code": "(testing \"carrot should be invalid\" (is (= 0 (to-decimal \"carrot\"))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "invalid-input-with-digits-is-decimal-0",
      "status": "error",
      "test_code": "(testing \"0a1b2c should be 0\" (is (= 0 (to-decimal \"0a1b2c\"))))"
    }
  ],
  "version": 2
}
